### ISSUE TITLE
im getting this error

### ISSUE THREAD

**Issue by spayse** [swimauger/upnpjs#1]
const igd = await upnp.discover();
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules

**Comment by swimauger** [comment]
Haha welcome to the world of Asynchronous JavaScript 😄 

Here take a look at this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

My documentation could be a little more clear about that, but you will probably want to wrap any await's in an asynchronous function like so:

```javascript
async function logExternalIPAdress() {
  const igd = await upnp.discover();
  console.log(await igd.getExternalIPAddress());
}
```

You may also want to take a look at this too https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by spayse** [comment]
thanks man, it worked but instead of returning an object with data it returned false even though i set to true.
